"""uk_cbam_initial_schema

Revision ID: 63314358988d
Revises: 
Create Date: 2026-04-10 16:52:07.018951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63314358988d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uk_cbam_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commodity_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('default_intensity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('includes_indirect', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uk_cbam_products_commodity_code'), 'uk_cbam_products', ['commodity_code'], unique=True)
    op.create_table('uk_ets_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarter', sa.String(length=10), nullable=False),
    sa.Column('price_gbp', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('installation_id', sa.String(length=100), nullable=True),
    sa.Column('data_status', sa.String(length=30), nullable=True),
    sa.Column('last_request_sent', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_data_received', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_suppliers_org', 'suppliers', ['org_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('cbam_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_liability', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('import_date', sa.Date(), nullable=False),
    sa.Column('import_value_gbp', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('quantity_tonnes', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('country_of_origin', sa.String(length=100), nullable=False),
    sa.Column('import_type', sa.String(length=30), nullable=True),
    sa.Column('data_source', sa.String(length=30), nullable=False),
    sa.Column('emissions_intensity_actual', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('emissions_intensity_default', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('verifier_name', sa.String(length=255), nullable=True),
    sa.Column('verification_date', sa.Date(), nullable=True),
    sa.Column('carbon_price_deduction_gbp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deduction_evidence_note', sa.Text(), nullable=True),
    sa.Column('uk_ets_rate_used', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('embedded_emissions_tco2e', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('cbam_liability_gbp', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cbam_liability_default_gbp', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('potential_saving_gbp', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_threshold_exempt', sa.Boolean(), nullable=True),
    sa.Column('exemption_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['uk_cbam_products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_imports_org_date', 'imports', ['org_id', 'import_date'], unique=False)
    op.create_index('idx_imports_supplier', 'imports', ['supplier_id'], unique=False)
    op.drop_table('cbam_imports')
    op.add_column('users', sa.Column('org_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'users', 'organisations', ['org_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role')
    op.drop_column('users', 'org_id')
    op.create_table('cbam_imports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hscn_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('origin_country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity_tonnes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('emission_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('embedded_emissions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('carbon_price_eur', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cbam_charge_eur', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('import_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('quarter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('declaration_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('supplier_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("(quarter::text = ANY (ARRAY['Q1'::character varying, 'Q2'::character varying, 'Q3'::character varying, 'Q4'::character varying]::text[])) OR quarter IS NULL", name='check_quarter'),
    sa.CheckConstraint("category::text = ANY (ARRAY['cement'::character varying, 'iron_steel'::character varying, 'aluminum'::character varying, 'fertilizers'::character varying, 'electricity'::character varying, 'hydrogen'::character varying]::text[])", name='check_cbam_category'),
    sa.CheckConstraint("declaration_status::text = ANY (ARRAY['pending'::character varying, 'declared'::character varying, 'verified'::character varying]::text[])", name='check_declaration_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='cbam_imports_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='cbam_imports_pkey')
    )
    op.drop_index('idx_imports_supplier', table_name='imports')
    op.drop_index('idx_imports_org_date', table_name='imports')
    op.drop_table('imports')
    op.drop_table('cbam_reports')
    op.drop_index('idx_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('idx_suppliers_org', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_table('uk_ets_prices')
    op.drop_index(op.f('ix_uk_cbam_products_commodity_code'), table_name='uk_cbam_products')
    op.drop_table('uk_cbam_products')
    op.drop_table('organisations')
    # ### end Alembic commands ###
